# An example configuration file for recode_st

log_level = "INFO" # Define the logging level here. Options are: DEBUG, INFO, WARNING, ERROR, CRITICAL
seed = 21122023    # Random seed for reproducibility

[io]
base_dir = "."                         # Base directory for the project (relative to the current working directory)
data_dir = "data"                      # Directory where the input data is stored (relative to base_dir)
output_dir = "analysis"                # Directory where the output will be saved (relative to base_dir)
xenium_dir = "xenium"                  # Directory containing Xenium data (relative to data_dir)
zarr_dir = "xenium.zarr"               # Directory where Zarr data will be stored (relative to data_dir)
area_path = "selected_cells_stats.csv" # Path to the CSV file containing selected cells statistics (relative to data_dir)
logging_path = "logs"                  # Directory where logs will be saved (relative to output_dir)

[modules.format_data]
module_name = "0_format" # Name of the module - will be used in the output directory name

[modules.quality_control]
module_name = "1_quality_control" # Name of the module - will be used in the output directory name
min_counts = 10                   # Minimum number of counts required for a cell to pass filtering
min_cells = 5                     # Minimum number of cells expressed required for a gene to pass filtering

[modules.dimension_reduction]
module_name = "2_dimension_reduction" # Name of the module - will be used in the output directory name

[modules.annotate]
module_name = "3_annotate" # Name of the module - will be used in the output directory name

[modules.view_images]
module_name = "4_view_images" # Name of the module - will be used in the output directory name
gene_list = [ # List of genes to visualize on tissue
    "EPCAM",
    "CD3D",
    "CD68",
    "PTPRC",
    "ACTA2",
]

[modules.spatial_statistics]
module_name = "5_spatial_stats" # Name of the module - will be used in the output directory name

[modules.muspan]
module_name = "6_muspan" # Name of the module - will be used in the output directory name
domain_name = "Xenium_lung_FFPE" # Name of the domain for MuSpAn analysis
transcripts_of_interest = [ # List of transcripts of interest for MuSpAn analysis
    "EPCAM",
    "CD3D",
    "CD68",
    "VWF",
    "PTPRC",
    "ACTA2",
]

[modules.muspan_spatial_stat]
module_name = "6_muspan"               # Name of the module - will be used in the output directory name
muspan_object = "muspan_object.muspan" # Name of the muspan object file
cluster_labels = "cell_type"           # Name of the cluster labels field to use for analysis

[modules.muspan_spatial_graph]
module_name = "6_muspan"               # Name of the module - will be used in the output directory name
muspan_object = "muspan_object.muspan" # Name of the muspan object file
min_edge_distance = 0                  # Minimum edge distance for spatial graphs
max_edge_distance = 45                 # Maximum edge distance for spatial graphs
distance_list = [10, 20, 50]           # List of distances for proximity networks
min_edge_distance_shape = 0            # Minimum edge distance for shape-based networks
max_edge_distance_shape = 1            # Maximum edge distance for shape-based networks
k_list = [2, 5, 10, 15]                # List of k values for KNN networks
