# An example configuration file for recode_st

log_level = "INFO" # Define the logging level here. Options are: DEBUG, INFO, WARNING, ERROR, CRITICAL
seed = 21122023    # Random seed for reproducibility

[io]
base_dir = "/Volumes/sep22/home/wet_lab/_Experiments/009_ST_Xenium" # Base directory for the project (relative to the current working directory)
data_dir = "data"                                                   # Directory where the input data is stored
output_dir = "out"                                                  # Directory where the output will be saved (relative to data_dir)
output_data_dir = "data"                                            # Directory where processed data will be saved (relative to output_dir)
xenium_dir = "xenium"                                               # Directory containing Xenium data (relative to data_dir)
zarr_dir = "xenium.zarr"                                            # Directory where Zarr data will be stored (relative to data_dir)
adata_dir = "adata"                                                 # Directory where AnnData objects will be saved (relative to output_data_dir)
area_path = "selected_cells_stats.csv"                              # Path to the CSV file containing selected cells statistics (relative to data_dir)
logging_path = "logs"                                               # Directory where logs will be saved (relative to output_dir)

[modules.quality_control]
module_name = "1_quality_control" # Name of the module - will be used in the output directory name
min_counts = 10                   # Minimum number of counts required for a cell to pass filtering
min_cells = 5                     # Minimum number of cells expressed required for a gene to pass filtering
min_cell_area = 25                # Minimum cell area to filter cells required for a cell to pass filtering
max_cell_area = 1000              # Maximum cell area to filter cells required for a cell to pass filtering
norm_approach = "scanpy_log"      # Normalization approach to use

[modules.dimension_reduction]
module_name = "2_dimension_reduction" # Name of the module - will be used in the output directory name
norm_approach = "scanpy_log"          # Normalization approach to use
subsample_data = true                 # Whether to subsample the data for development purposes
n_comps = 30                          # number of principal components to compute
n_neighbors = 30                      # number of neighbors for the neighborhood graph
resolution = 0.5                      # resolution for leiden clustering
cluster_name = "leiden"               # name of the cluster column in adata.obs
