# An example configuration file for recode_st

# --- Global Settings ---
log_level = "INFO"
seed = 42

# --- Input / Output Configuration ---
[io]
base_dir = "/path/to/project"
data_dir = "data"
output_dir = "out"
xenium_dir = "xenium"
output_data_dir = "processed_data"
zarr_dir = "xenium.zarr"
adata_dir = "adata"
area_path = "selected_cells_stats.csv"
logging_dir = "logs"

# --- Modules Configuration ---
[modules.format_data]
module_name = "format_data"

[modules.subsample_data]
module_name = "subsample"
n_cells = 5000
replace = false

[modules.quality_control]
module_name = "quality_control"
subsample_data = false
min_counts = 200
min_cells = 3
min_cell_area = 50
max_cell_area = 2000
norm_approach = "cell_area"

[modules.dimension_reduction]
module_name = "dimension_reduction"
subsample_strategy = "compute"
n_pca = 30
n_neighbors = 15
resolution = 0.5
cluster_name = "leiden_clusters"
norm_approach = "scanpy_log"

[modules.integrate]
module_name = "integrate"
method = "ingest"

[modules.annotate]
module_name = "annotate"
cluster_name = "leiden_clusters"
new_clusters = "annotated_clusters"

[modules.view_images]
module_name = "view_images"
gene_list = ["CD3E", "EPCAM", "PECAM1", "MKI67"]

[modules.muspan]
module_name = "muspan"
domain_name = "tumor_microenvironment"
transcripts_of_interest = ["CXCL13", "CXCR5", "CD8A"]
adata_cell_id = "cell_id"
cluster_labels = "cell_type"

[modules.muspan_spatial_stat]
module_name = "muspan_spatial_stat"
muspan_object = "muspan_object.pkl"
cluster_labels = "cell_type"

[modules.muspan_spatial_graph]
module_name = "muspan_spatial_graph"
muspan_object = "muspan_object.pkl"
min_edge_distance = 10
max_edge_distance = 50
distance_list = [10, 20, 30, 40, 50]
min_edge_distance_shape = 5
max_edge_distance_shape = 25
k_list = [5, 10, 15]
